#!/bin/bash

# 프로젝트 설정 자동화 스크립트
# 각 사용자가 자신의 프로젝트 ID로 설정할 수 있도록 지원

set -e

# 색상 코드
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}===============================================${NC}"
echo -e "${GREEN}    Senior MHealth 프로젝트 설정 스크립트${NC}"
echo -e "${GREEN}===============================================${NC}"

# 1. 프로젝트 ID 입력 받기
if [ -z "$GCP_PROJECT_ID" ]; then
    echo -e "\n${YELLOW}Google Cloud 프로젝트 ID를 입력하세요:${NC}"
    read -p "Project ID: " GCP_PROJECT_ID
fi

# 2. 프로젝트 번호 가져오기
echo -e "\n${YELLOW}프로젝트 정보 확인 중...${NC}"
GCP_PROJECT_NUMBER=$(gcloud projects describe $GCP_PROJECT_ID --format="value(projectNumber)" 2>/dev/null || echo "")

if [ -z "$GCP_PROJECT_NUMBER" ]; then
    echo -e "${RED}프로젝트를 찾을 수 없습니다. 프로젝트 ID를 확인하세요.${NC}"
    exit 1
fi

# 3. 리전 설정
DEFAULT_REGION="us-central1"
echo -e "\n${YELLOW}배포 리전을 선택하세요 (기본값: $DEFAULT_REGION):${NC}"
echo "1) us-central1 (미국 중부) - 권장"
echo "2) asia-northeast3 (서울)"
echo "3) europe-west1 (벨기에)"
echo "4) 직접 입력"
read -p "선택 [1-4]: " region_choice

case $region_choice in
    2) GCP_REGION="asia-northeast3" ;;
    3) GCP_REGION="europe-west1" ;;
    4)
        read -p "리전 입력: " GCP_REGION
        ;;
    *) GCP_REGION=$DEFAULT_REGION ;;
esac

# 4. .env 파일 생성
echo -e "\n${YELLOW}.env 파일 생성 중...${NC}"

cat > .env << EOF
# ====================================
# Generated by setup-project.sh
# Project: $GCP_PROJECT_ID
# Generated at: $(date)
# ====================================

# === GCP Project Configuration ===
GCP_PROJECT_ID=$GCP_PROJECT_ID
GCP_PROJECT_NUMBER=$GCP_PROJECT_NUMBER
GCP_REGION=$GCP_REGION

# === Firebase Configuration ===
FIREBASE_PROJECT_ID=$GCP_PROJECT_ID
FIREBASE_AUTH_DOMAIN=${GCP_PROJECT_ID}.firebaseapp.com
FIREBASE_STORAGE_BUCKET=${GCP_PROJECT_ID}.firebasestorage.app
FIREBASE_MESSAGING_SENDER_ID=$GCP_PROJECT_NUMBER

# === Service Names ===
SERVICE_NAME=${GCP_PROJECT_ID}-ai-service
API_SERVICE_NAME=${GCP_PROJECT_ID}-api-service

# === Storage ===
STORAGE_BUCKET=${GCP_PROJECT_ID}.appspot.com

# === Database Configuration ===
BIGQUERY_DATASET=senior_mhealth_analytics
BIGQUERY_LOCATION=$GCP_REGION

# === Environment ===
ENVIRONMENT=development
LOG_LEVEL=INFO
EOF

echo -e "${GREEN}✅ .env 파일이 생성되었습니다.${NC}"

# 5. project.config.json 파일 생성
echo -e "\n${YELLOW}project.config.json 파일 생성 중...${NC}"

cat > project.config.json << EOF
{
  "project": {
    "id": "$GCP_PROJECT_ID",
    "name": "$GCP_PROJECT_ID",
    "region": "$GCP_REGION",
    "location": "$GCP_REGION"
  },
  "firebase": {
    "projectId": "$GCP_PROJECT_ID",
    "storageBucket": "${GCP_PROJECT_ID}.firebasestorage.app",
    "messagingSenderId": "$GCP_PROJECT_NUMBER"
  },
  "cloud": {
    "projectNumber": "$GCP_PROJECT_NUMBER"
  },
  "database": {
    "cloudSqlConnectionName": "${GCP_PROJECT_ID}:${GCP_REGION}:main-instance",
    "cloudSqlInstance": "main-instance",
    "bigQueryDataset": "senior_mhealth_analytics"
  },
  "services": {
    "aiService": {
      "name": "${GCP_PROJECT_ID}-ai-service",
      "url": "https://${GCP_PROJECT_ID}-ai-service-${GCP_REGION}.run.app"
    },
    "apiService": {
      "name": "${GCP_PROJECT_ID}-api-service",
      "url": "https://${GCP_PROJECT_ID}-api-service-${GCP_REGION}.run.app"
    }
  }
}
EOF

echo -e "${GREEN}✅ project.config.json 파일이 생성되었습니다.${NC}"

# 5-1. .env.docker 파일 생성 (Docker Compose용)
echo -e "\n${YELLOW}.env.docker 파일 생성 중...${NC}"

cat > .env.docker << EOF
# Docker Compose 환경 변수 설정
# Generated by setup-project.sh at $(date)

# === PostgreSQL 설정 ===
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=senior_mhealth_dev
POSTGRES_PORT=5432

# === Redis 설정 ===
REDIS_PORT=6379

# === Backend API Service ===
API_PORT=8000

# === Backend AI Service ===
AI_PORT=8001

# === Frontend Web ===
WEB_PORT=3000

# === pgAdmin 설정 ===
PGADMIN_EMAIL=admin@senior-mhealth.local
PGADMIN_PASSWORD=admin
PGADMIN_PORT=5050

# === GCP/Firebase 설정 ===
GCP_PROJECT_ID=$GCP_PROJECT_ID
FIREBASE_API_KEY=\${FIREBASE_API_KEY:-demo-api-key}

# === 개발 환경 설정 ===
NODE_ENV=development
ENVIRONMENT=development
EOF

echo -e "${GREEN}✅ .env.docker 파일이 생성되었습니다.${NC}"

# 6. API 키 설정 안내
echo -e "\n${YELLOW}=== API 키 설정 안내 ===${NC}"
echo "다음 API 키들을 .env 파일에 직접 추가해주세요:"
echo ""
echo "GEMINI_API_KEY=your-gemini-api-key"
echo "OPENAI_API_KEY=your-openai-api-key (선택사항)"
echo "FIREBASE_API_KEY=your-firebase-api-key"
echo ""
echo "API 키 생성 방법:"
echo "- Gemini API: https://makersuite.google.com/app/apikey"
echo "- Firebase: Firebase Console > 프로젝트 설정 > 일반"

# 7. 프로젝트 설정
echo -e "\n${YELLOW}Google Cloud 프로젝트 설정 중...${NC}"

# 현재 프로젝트 설정
gcloud config set project $GCP_PROJECT_ID

# 필요한 API 활성화
echo -e "\n${YELLOW}필요한 API 활성화 중...${NC}"
apis=(
    "run.googleapis.com"
    "cloudbuild.googleapis.com"
    "containerregistry.googleapis.com"
    "firestore.googleapis.com"
    "storage-component.googleapis.com"
    "bigquery.googleapis.com"
)

for api in "${apis[@]}"; do
    echo "Enabling $api..."
    gcloud services enable $api --quiet || true
done

# 8. Firebase 초기화 확인
echo -e "\n${YELLOW}Firebase 프로젝트 초기화...${NC}"
if command -v firebase &> /dev/null; then
    firebase use $GCP_PROJECT_ID || firebase use --add $GCP_PROJECT_ID
else
    echo -e "${YELLOW}Firebase CLI가 설치되지 않았습니다.${NC}"
    echo "설치: npm install -g firebase-tools"
fi

# 9. 의존성 설치 옵션
echo -e "\n${YELLOW}=== 의존성 설치 ===${NC}"
read -p "의존성을 자동으로 설치하시겠습니까? (y/N): " install_deps

if [[ "$install_deps" =~ ^[Yy]$ ]]; then
    echo -e "\n${YELLOW}Backend Functions 의존성 설치 중...${NC}"
    if [ -d "backend/functions" ]; then
        (cd backend/functions && npm install) || echo -e "${RED}❌ Backend functions 설치 실패${NC}"
    fi

 # Offer to install service account key
 echo -e "\n${YELLOW}서비스 계정 키 설치 안내${NC}"
 read -p "서비스 계정 키 파일(.json)을 설치하시겠습니까? (권장: 예) (y/N): " install_sa
 if [[ "$install_sa" =~ ^[Yy]$ ]]; then
   read -p "서비스 계정 키 파일 경로를 입력하세요 (예: ~/Downloads/my-key.json): " sa_src
   sa_src=${sa_src/#\~/$HOME}
   echo -e "설치 중... (대상 경로: backend/service-account-key.json)"
   bash setup/scripts/install-service-account.sh "$sa_src" backend/service-account-key.json || echo -e "${RED}서비스 계정 설치에 실패했습니다${NC}"
   echo -e "${GREEN}서비스 계정 키 설치가 완료되었거나 중단되었습니다.${NC}"
 else
   echo -e "${YELLOW}건너뜁니다. 설치는 나중에 'setup/scripts/install-service-account.sh'를 사용하세요.${NC}"
 fi
    echo -e "\n${YELLOW}Frontend Web 의존성 설치 중...${NC}"
    if [ -d "frontend/web" ]; then
        (cd frontend/web && npm install) || echo -e "${RED}❌ Frontend web 설치 실패${NC}"
    fi

    echo -e "\n${YELLOW}Frontend Mobile 의존성 설치 중...${NC}"
    if [ -d "frontend/mobile" ] && command -v flutter &> /dev/null; then
        (cd frontend/mobile && flutter pub get) || echo -e "${RED}❌ Flutter 설치 실패${NC}"
    elif [ -d "frontend/mobile" ]; then
        echo -e "${YELLOW}⚠️ Flutter CLI가 설치되지 않았습니다${NC}"
    fi

    echo -e "${GREEN}✅ 의존성 설치 완료${NC}"
else
    echo -e "${YELLOW}⏭️  의존성 설치를 건너뜁니다${NC}"
fi

# 10. 설정 검증
echo -e "\n${YELLOW}=== 설정 검증 ===${NC}"
if [ -f "scripts/validate-config.sh" ]; then
    echo "설정 검증 스크립트 실행 중..."
    bash scripts/validate-config.sh || echo -e "${YELLOW}⚠️ 일부 검증 실패 (개발은 계속 가능합니다)${NC}"
else
    echo -e "${YELLOW}⚠️ validate-config.sh를 찾을 수 없습니다${NC}"
fi

# 11. 완료
echo -e "\n${GREEN}===============================================${NC}"
echo -e "${GREEN}✅ 프로젝트 설정이 완료되었습니다!${NC}"
echo -e "${GREEN}===============================================${NC}"
echo ""
echo "📋 생성된 파일:"
echo "  ✓ .env                    - 환경 변수"
echo "  ✓ project.config.json    - 프로젝트 설정"
echo "  ✓ .env.docker            - Docker Compose 설정"
echo ""
echo "📊 프로젝트 정보:"
echo "  • 프로젝트 ID: $GCP_PROJECT_ID"
echo "  • 프로젝트 번호: $GCP_PROJECT_NUMBER"
echo "  • 리전: $GCP_REGION"
echo ""
echo "📝 다음 단계:"
echo ""
echo "  1️⃣  API 키 추가 (필수)"
echo "     .env 파일을 열어 다음 키들을 추가하세요:"
echo "     - GEMINI_API_KEY=your-key"
echo "     - FIREBASE_API_KEY=your-key"
echo ""
if [[ ! "$install_deps" =~ ^[Yy]$ ]]; then
echo "  2️⃣  의존성 설치"
echo "     cd backend/functions && npm install"
echo "     cd frontend/web && npm install"
echo "     cd frontend/mobile && flutter pub get"
echo ""
fi
echo "  3️⃣  로컬 개발 환경 시작"
echo "     🐳 Docker 사용 (권장):"
echo "        docker-compose up -d"
echo "        docker-compose logs -f"
echo ""
echo "     또는 직접 실행:"
echo "        firebase emulators:start        # Firebase 에뮬레이터"
echo "        cd frontend/web && npm run dev  # 프론트엔드"
echo ""
echo "  4️⃣  VSCode 설정 (권장)"
echo "     VSCode를 열면 권장 확장 프로그램 설치 알림이 표시됩니다"
echo "     .vscode/extensions.json에 필요한 확장 목록이 있습니다"
echo ""
echo "  5️⃣  CI/CD 설정 (GitHub 사용 시)"
echo "     GitHub 저장소 Settings > Secrets and variables > Actions에서"
echo "     다음 Secrets를 추가하세요:"
echo ""
echo "     필수 Secrets:"
echo "     • GCP_PROJECT_ID=$GCP_PROJECT_ID"
echo "     • GCP_REGION=$GCP_REGION"
echo "     • GCP_SA_KEY=<서비스 계정 키 JSON>"
echo "     • FIREBASE_TOKEN=<firebase login:ci 결과>"
echo "     • FIREBASE_PROJECT_ID=$GCP_PROJECT_ID"
echo "     • FIREBASE_API_KEY=<Firebase API 키>"
echo ""
echo "     선택 Secrets (Vercel 배포 시):"
echo "     • VERCEL_TOKEN=<Vercel 토큰>"
echo "     • VERCEL_ORG_ID=<Vercel 조직 ID>"
echo "     • VERCEL_PROJECT_ID=<Vercel 프로젝트 ID>"
echo ""
echo "     GitHub Actions 워크플로우:"
echo "     • .github/workflows/validate-config.yml - 설정 검증"
echo "     • .github/workflows/deploy.yml          - 자동 배포"
echo "     • .github/workflows/pr-checks.yml       - PR 체크"
echo ""
echo "  6️⃣  배포"
echo "     firebase deploy                             # Functions + Hosting"
echo "     cd backend/api-service && gcloud run deploy # API Service"
echo "     cd backend/ai-service && gcloud run deploy  # AI Service"
echo ""
echo "📚 자세한 문서:"
echo "  • README.md           - 프로젝트 개요 및 시작 가이드"
echo "  • SETUP_GUIDE.md      - 상세 설정 가이드"
echo "  • DOCKER_SETUP.md     - Docker 환경 가이드"
echo "  • docs/               - 추가 문서"
echo ""
echo "🔗 유용한 명령어:"
echo "  • bash scripts/validate-config.sh  - 설정 검증"
echo "  • docker-compose up -d             - 전체 스택 시작"
echo "  • docker-compose logs -f           - 로그 확인"
echo "  • firebase emulators:start         - Firebase 에뮬레이터"
echo ""
echo -e "${GREEN}🎉 설정이 완료되었습니다! 즐거운 개발 되세요!${NC}"
